compositor-android: fix build flags
When adding a C++ file to the build, I forgot to set CXXFLAGS for it,
triggering the error:

android-framebuffer.h:26:21: fatal error: EGL/egl.h: No such file or
directory

I never hit this, because I have EGL headers installed also in my
system, rather than only in $prefix.

Fix this by setting the CXXFLAGS for the android backend.

Reported-by: Scott Moreau <oreaus@gmail.com>
Reported-by: Tiago Vignatti <tiago.vignatti@intel.com>
Signed-off-by: Pekka Paalanen <ppaalanen@gmail.com>